# Using Autograd In Torch

In [2]:
# Import

import torch

In [15]:
# set up a tensor.

x = torch.randn(3, requires_grad = True)
print(x)

tensor([ 0.6471, -1.2873, -0.4827], requires_grad=True)


In [16]:
# Adding a number to x. 

y = x + 2
print(y)

tensor([2.6471, 0.7127, 1.5173], grad_fn=<AddBackward0>)


In [9]:
# Another operation on the tensor. 

z = y*y*2

# The mean

z = z.mean()

In [10]:
# If we want to calculate the gradiant of z.

z.backward()

# Print out te gradient of x

print(x.grad)

tensor([2.0474, 2.1676, 3.8958])


In [12]:
# Another operation on the tensor. 

z = y*y*2

# Not doing the mean of z this time. 

v = torch.tensor([0.1,1.0,0.01], dtype = torch.float32)

z.backward(v)

In [17]:
# To remove any memory of the grad. 

y = x.detach()
y

# Or this method. 

with torch.no_grad():
    y = x + 2 
    print(y)

tensor([2.6471, 0.7127, 1.5173])
